package com.xingyi.logistic.business.service;

import com.xingyi.logistic.business.model.UserThirdPartyDetail;
import com.xingyi.logistic.business.model.UserThirdPartyDetailQuery;

/**
 * auto generated by code helper on 2018-11-04.
 */
public interface UserThirdPartyDetailService extends BaseService<UserThirdPartyDetail, UserThirdPartyDetailQuery> {


}