package com.szmtjk.web.controller;

import com.szmtjk.business.model.ExamReservation;
import com.szmtjk.business.model.ExamReservationQuery;
import com.szmtjk.web.controller.base.BaseCRUDController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * auto generated by code helper on 2019-01-22.
 */
@RestController
@RequestMapping("/examReservation")
public class ExamReservationController extends BaseCRUDController<ExamReservation, ExamReservationQuery> {

}