package com.szmtjk.web.controller;

import com.szmtjk.business.model.User;
import com.szmtjk.business.model.UserQuery;
import com.szmtjk.web.controller.base.BaseCRUDController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * auto generated by code helper on 2019-01-05.
 */
@RestController
@RequestMapping("/user")
public class UserController extends BaseCRUDController<User, UserQuery> {

}