package com.xingyi.logistic.business.model;


import com.xingyi.logistic.business.bean.BaseModelAndDO;

/**
 * auto generated by code helper on 2018-11-04.
 */
public class BaseUserThirdPartyDetail extends BaseModelAndDO {
    /**
     * id
     */
    private Long id;
    /**
     * thirdType
     */
    private Integer thirdType;
    /**
     * thirdId
     */
    private String thirdId;
    /**
     * appType
     */
    private Integer appType;
    /**
     * thirdId2
     */
    private String thirdId2;
    /**
     * extra
     */
    private String extra;
    /**
     * created
     */
    private Long created;
    /**
     * updated
     */
    private Long updated;
    /**
     * isDeleted
     */
    private Integer isDeleted;

    public Long getId() {
        return id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public Integer getThirdType() {
        return thirdType;
    }

    public void setThirdType(Integer thirdType){
        this.thirdType = thirdType;
    }

    public String getThirdId() {
        return thirdId;
    }

    public void setThirdId(String thirdId){
        this.thirdId = thirdId;
    }

    public Integer getAppType() {
        return appType;
    }

    public void setAppType(Integer appType){
        this.appType = appType;
    }

    public String getThirdId2() {
        return thirdId2;
    }

    public void setThirdId2(String thirdId2){
        this.thirdId2 = thirdId2;
    }

    public String getExtra() {
        return extra;
    }

    public void setExtra(String extra){
        this.extra = extra;
    }

    public Long getCreated() {
        return created;
    }

    public void setCreated(Long created){
        this.created = created;
    }

    public Long getUpdated() {
        return updated;
    }

    public void setUpdated(Long updated){
        this.updated = updated;
    }

    public Integer getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Integer isDeleted){
        this.isDeleted = isDeleted;
    }

}