package com.xingyi.logistic.business.model;


import com.xingyi.logistic.business.bean.BaseQueryPage;

/**
 * auto generated by code helper on 2018-11-04.
 */
public class UserThirdPartyDetailQuery extends BaseQueryPage {

}
