package com.xingyi.logistic.business.db.entity;


import com.xingyi.logistic.business.bean.BaseDBQueryPage;

/**
 * auto generated by code helper on 2018-11-04.
 */
public class UserThirdPartyDetailDBQuery extends BaseDBQueryPage {

}
