package com.xingyi.logistic.business.db.entity;

import com.xingyi.logistic.business.model.BaseUserThirdPartyDetail;

/**
 * auto generated by code helper on 2018-11-04.
 */
public class UserThirdPartyDetailDO extends BaseUserThirdPartyDetail {

}
