package com.szmtjk.business.service;

import com.szmtjk.business.model.ExamReservation;
import com.szmtjk.business.model.ExamReservationQuery;
import com.szmtjk.business.service.base.BaseService;

/**
 * auto generated by code helper on 2019-01-22.
 */
public interface ExamReservationService extends BaseService<ExamReservation, ExamReservationQuery> {


}