package com.szmtjk.business.service;

import com.szmtjk.business.model.FileImportStatus;
import com.szmtjk.business.model.FileImportStatusQuery;
import com.szmtjk.business.service.base.BaseService;

/**
 * auto generated by code helper on 2019-03-04.
 */
public interface FileImportStatusService extends BaseService<FileImportStatus, FileImportStatusQuery> {


}