package com.szmtjk.business.service;

import com.szmtjk.business.model.User;
import com.szmtjk.business.model.UserQuery;
import com.szmtjk.business.service.base.BaseService;

/**
 * auto generated by code helper on 2019-01-05.
 */
public interface UserService extends BaseService<User, UserQuery> {


}