package com.xingyi.logistic.business.db.dao;

import com.xingyi.logistic.business.db.dao.base.BaseDAO;
import com.xxx.boot.jdbc.annotation.Dao;
import com.xingyi.logistic.business.db.entity.UserThirdPartyDetailDBQuery;
import com.xingyi.logistic.business.db.entity.UserThirdPartyDetailDO;

/**
 * auto generated by code helper on 2018-11-04.
 */
@Dao
public interface UserThirdPartyDetailDAO extends BaseDAO<UserThirdPartyDetailDO, UserThirdPartyDetailDBQuery> {

}