package com.szmtjk.business.db.dao;

import com.xxx.boot.jdbc.annotation.Dao;
import com.szmtjk.business.db.dao.base.BaseDAO;
import com.szmtjk.business.db.entity.ExamReservationDBQuery;
import com.szmtjk.business.db.entity.ExamReservationDO;

/**
 * auto generated by code helper on 2019-01-22.
 */
@Dao
public interface ExamReservationDAO extends BaseDAO<ExamReservationDO, ExamReservationDBQuery> {

}