package com.szmtjk.business.db.dao;

import com.xxx.boot.jdbc.annotation.Dao;
import com.szmtjk.business.db.dao.base.BaseDAO;
import com.szmtjk.business.db.entity.FileImportStatusDBQuery;
import com.szmtjk.business.db.entity.FileImportStatusDO;

/**
 * auto generated by code helper on 2019-03-04.
 */
@Dao
public interface FileImportStatusDAO extends BaseDAO<FileImportStatusDO, FileImportStatusDBQuery> {

}