package com.szmtjk.business.db.dao;

import com.xxx.boot.jdbc.annotation.Dao;
import com.szmtjk.business.db.dao.base.BaseDAO;
import com.szmtjk.business.db.entity.UserDBQuery;
import com.szmtjk.business.db.entity.UserDO;

/**
 * auto generated by code helper on 2019-01-05.
 */
@Dao
public interface UserDAO extends BaseDAO<UserDO, UserDBQuery> {

}