package com.szmtjk.business.converter;

import com.szmtjk.business.converter.base.QueryConditionConverter;
import com.szmtjk.business.db.entity.ExamReservationDBQuery;
import com.szmtjk.business.model.ExamReservationQuery;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Component;

/**
 * auto generated by code helper on 2019-01-22.
 */
@Component
public class ExamReservationQueryConverter extends QueryConditionConverter<ExamReservationQuery, ExamReservationDBQuery> {

    @Override
    public ExamReservationDBQuery toDOCondition(ExamReservationQuery src) {
        ExamReservationDBQuery dst = new ExamReservationDBQuery();
        if (src != null) {
            paginationConvert(src, dst);
            BeanUtils.copyProperties(src, dst);
        }
        return dst;
    }

}