package com.szmtjk.business.converter;

import com.szmtjk.business.converter.base.ModelConverter;
import com.szmtjk.business.db.entity.ExamReservationDO;
import com.szmtjk.business.model.ExamReservation;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Component;

/**
 * auto generated by code helper on 2019-01-22.
 */
@Component
public class ExamReservationConverter extends ModelConverter<ExamReservationDO, ExamReservation> {

    @Override
    public ExamReservationDO toDataObject(ExamReservation src) {
        ExamReservationDO dst = new ExamReservationDO();
        if (src != null) {
            BeanUtils.copyProperties(src, dst);
        }
        return dst;
    }

    @Override
    public ExamReservation toModel(ExamReservationDO src) {
        ExamReservation dst = new ExamReservation();
        if (src != null) {
            BeanUtils.copyProperties(src, dst);
        }
        return dst;
    }

}