package com.szmtjk.business.converter;

import com.szmtjk.business.converter.base.ModelConverter;
import com.szmtjk.business.db.entity.FileImportStatusDO;
import com.szmtjk.business.model.FileImportStatus;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Component;

/**
 * auto generated by code helper on 2019-03-04.
 */
@Component
public class FileImportStatusConverter extends ModelConverter<FileImportStatusDO, FileImportStatus> {

    @Override
    public FileImportStatusDO toDataObject(FileImportStatus src) {
        FileImportStatusDO dst = new FileImportStatusDO();
        if (src != null) {
            BeanUtils.copyProperties(src, dst);
        }
        return dst;
    }

    @Override
    public FileImportStatus toModel(FileImportStatusDO src) {
        FileImportStatus dst = new FileImportStatus();
        if (src != null) {
            BeanUtils.copyProperties(src, dst);
        }
        return dst;
    }

}