package com.szmtjk.business.converter;

import com.szmtjk.business.converter.base.QueryConditionConverter;
import com.szmtjk.business.db.entity.UserDBQuery;
import com.szmtjk.business.model.UserQuery;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Component;

/**
 * auto generated by code helper on 2019-01-05.
 */
@Component
public class UserQueryConverter extends QueryConditionConverter<UserQuery, UserDBQuery> {

    @Override
    public UserDBQuery toDOCondition(UserQuery src) {
        UserDBQuery dst = new UserDBQuery();
        if (src != null) {
            paginationConvert(src, dst);
            BeanUtils.copyProperties(src, dst);
        }
        return dst;
    }

}