package com.xingyi.logistic.business.service.impl;

import com.xingyi.logistic.business.db.dao.base.BaseDAO;
import com.xingyi.logistic.business.model.UserThirdPartyDetail;
import com.xingyi.logistic.business.model.UserThirdPartyDetailQuery;
import com.xingyi.logistic.business.service.base.BaseCRUDService;
import com.xingyi.logistic.business.service.base.ModelConverter;
import com.xingyi.logistic.business.service.base.QueryConditionConverter;
import com.xingyi.logistic.business.db.entity.UserThirdPartyDetailDBQuery;
import com.xingyi.logistic.business.db.entity.UserThirdPartyDetailDO;
import com.xingyi.logistic.business.service.UserThirdPartyDetailService;
import org.springframework.stereotype.Service;

/**
 * auto generated by code helper on 2018-11-04.
 */
@Service
public class UserThirdPartyDetailServiceImpl extends BaseCRUDService<UserThirdPartyDetailDO, UserThirdPartyDetail, UserThirdPartyDetailDBQuery, UserThirdPartyDetailQuery> implements UserThirdPartyDetailService {
    @Override
    protected ModelConverter<UserThirdPartyDetailDO, UserThirdPartyDetail> getModelConverter() {
        return null;
    }

    @Override
    protected BaseDAO<UserThirdPartyDetailDO, UserThirdPartyDetailDBQuery> getDAO() {
        return null;
    }

    @Override
    protected QueryConditionConverter<UserThirdPartyDetailQuery, UserThirdPartyDetailDBQuery> getConditionConverter() {
        return null;
    }
}