spring:
  profiles:
    active: @profiles@

---
# You can change the default http port
server:
  port: 16722
  contextPath: /xyl

fee:
  rule: 0

# default db config
druid:
  group:
    defaultGroup: d_myc
    balance: robin
  datasource:
    - identity: myc_master
      group: d_myc
      role: master
      driverClassName: com.mysql.jdbc.Driver
      mapperLocations: classpath*:sqlMap/**/*Mapper.xml
      url: jdbc:mysql://127.0.0.1:3306/xyl?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: uAiqwVwjJ8-i
      initialSize: 5
      filters: stat
      maxActive: 8
      minIdle: 5
      maxWait: 50000
      validationQuery: SELECT 1


# active mq gps real
spring:
  activemq:
    broker-url: tcp://192.168.0.253:61616
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
  pid:
    file: pid.file
xyl:
  upload:
    baseDir: /data/pic/upload

# OAuth weixin
oauth:
  weixin:
    appId: wx716e867a8dfc27bb
    secretKey: 39a1e707862681e0690dfb6336e6dc87

wechat:
  appSecretConfigList:
    -
      appType: 1  # 公众号
      appId: wx65b6b370eb08f5fa
      appSecret: 0d7139ff0e7a7b762bec805fb2d4c13a
    -
      appType: 2  # 小程序
      appId: wx95ec521df9ec5a9e
      appSecret: 4a034346e26c946b48b2a75c2a290b24

# Different profiles' configuration
---
spring:
  profiles: dev


---
spring:
  profiles: prd

druid:
  datasource:
    - identity: myc_master
      group: d_myc
      role: master
      driverClassName: com.mysql.jdbc.Driver
      mapperLocations: classpath*:sqlMap/**/*Mapper.xml
      url: jdbc:mysql://127.0.0.1:3306/xyl?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: uAiqwVwjJ8-i
      initialSize: 5
      filters: stat
      maxActive: 8
      minIdle: 5
      maxWait: 50000
      validationQuery: SELECT 1
