spring:
  profiles:
    active: @profiles@

---
# You can change the default http port
server:
  port: 16722
  contextPath: /xyl

fee:
  rule: 0

# default db config
druid:
  group:
    defaultGroup: d_myc
    balance: robin
  datasource:
    - identity: myc_master
      group: d_myc
      role: master
      driverClassName: com.mysql.jdbc.Driver
      mapperLocations: classpath*:sqlMap/**/*Mapper.xml
      url: jdbc:mysql://47.100.45.229:3306/xyl?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: uAiqwVwjJ8-i
      initialSize: 5
      filters: stat
      maxActive: 8
      minIdle: 5
      maxWait: 50000
      validationQuery: SELECT 1


# active mq
spring:
  activemq:
    broker-url: tcp://183.246.204.251:61689
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
  pid:
    file: pid.file
xyl:
  upload:
    baseDir: /upload

# OAuth weixin
oauth:
  weixin:
    appId: wx716e867a8dfc27bb
    secretKey: 39a1e707862681e0690dfb6336e6dc87

aa:
  bb: default

# Different profiles' configuration
---
spring:
  profiles: dev

aa:
  bb: dev1

---
spring:
  profiles: prd

aa:
  bb: prd1

druid:
  datasource:
    - identity: myc_master
      group: d_myc
      role: master
      driverClassName: com.mysql.jdbc.Driver
      mapperLocations: classpath*:sqlMap/**/*Mapper.xml
      url: jdbc:mysql://47.100.45.229:3306/xyl?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: uAiqwVwjJ8-i
      initialSize: 5
      filters: stat
      maxActive: 8
      minIdle: 5
      maxWait: 50000
      validationQuery: SELECT 1