spring:
  profiles:
    active: @profiles@

tempUser:
  userNamePass:
    - hjj@hjj001
    - hzh@hzh002
    - pzh@pzh003
    - guest@guest001
---
# You can change the default http port
server:
  port: 16721
  contextPath: /xyl

logging:
  config: logback.xml

fee:
  rule: 0

# default db config
druid:
  group:
    defaultGroup: d_myc
    balance: robin
  datasource:
    - identity: myc_master
      group: d_myc
      role: master
      driverClassName: com.mysql.jdbc.Driver
      mapperLocations: classpath*:sqlMap/**/*Mapper.xml
      url: jdbc:mysql://127.0.0.1:3306/xyl?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      initialSize: 5
      filters: stat
      maxActive: 8
      minIdle: 5
      maxWait: 50000
      validationQuery: SELECT 1

# Different profiles' configuration
---
spring:
  profiles: dev

---
spring:
  profiles: prd

druid:
  datasource:
    password: 5678rtyU