package com.szmtjk.business.service.impl;

import com.szmtjk.business.db.entity.ExamReservationDBQuery;
import com.szmtjk.business.db.entity.ExamReservationDO;
import com.szmtjk.business.model.ExamReservation;
import com.szmtjk.business.model.ExamReservationQuery;
import com.szmtjk.business.service.ExamReservationService;
import com.szmtjk.business.service.base.BaseCRUDService;
import org.springframework.stereotype.Service;

/**
 * auto generated by code helper on 2019-01-22.
 */
@Service
public class ExamReservationServiceImpl extends BaseCRUDService<ExamReservationDO, ExamReservation, ExamReservationDBQuery, ExamReservationQuery> implements ExamReservationService {

}