package com.szmtjk.business.service.impl;

import com.szmtjk.business.db.entity.FileImportStatusDBQuery;
import com.szmtjk.business.db.entity.FileImportStatusDO;
import com.szmtjk.business.model.FileImportStatus;
import com.szmtjk.business.model.FileImportStatusQuery;
import com.szmtjk.business.service.FileImportStatusService;
import com.szmtjk.business.service.base.BaseCRUDService;
import org.springframework.stereotype.Service;

/**
 * auto generated by code helper on 2019-03-04.
 */
@Service
public class FileImportStatusServiceImpl extends BaseCRUDService<FileImportStatusDO, FileImportStatus, FileImportStatusDBQuery, FileImportStatusQuery> implements FileImportStatusService {

}