package com.szmtjk.business.service.impl;

import com.szmtjk.business.db.entity.UserDBQuery;
import com.szmtjk.business.db.entity.UserDO;
import com.szmtjk.business.model.User;
import com.szmtjk.business.model.UserQuery;
import com.szmtjk.business.service.UserService;
import com.szmtjk.business.service.base.BaseCRUDService;
import org.springframework.stereotype.Service;

/**
 * auto generated by code helper on 2019-01-05.
 */
@Service
public class UserServiceImpl extends BaseCRUDService<UserDO, User, UserDBQuery, UserQuery> implements UserService {

}