package com.szmtjk.business.bean;

import com.szmtjk.business.bean.base.BaseModelAndDO;

import java.io.Serializable;

/**
 * auto generated by code helper on 2019-03-04.
 */
public class BaseFileImportStatus extends BaseModelAndDO {
    /**
     * id
     */
    private Long id;
    /**
     * 导入业务类型  1：预约文件   2：体检报告
     */
    private Integer bizType;
    /**
     * 文件名
     */
    private String fileName;
    /**
     * 文件批次号
     */
    private String fileNo;
    /**
     * 文件导入状态  10：上传成功   20：处理成功  30：处理失败
     */
    private Integer status;
    /**
     * 处理结果提示
     */
    private String tip;
    /**
     * created
     */
    private Long created;
    /**
     * updated
     */
    private Long updated;
    /**
     * isDeleted
     */
    private Integer isDeleted;

    public Long getId() {
        return id;
    }

    public void setId(Long id){
        this.id = id;
    }

    public Integer getBizType() {
        return bizType;
    }

    public void setBizType(Integer bizType){
        this.bizType = bizType;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName){
        this.fileName = fileName;
    }

    public String getFileNo() {
        return fileNo;
    }

    public void setFileNo(String fileNo){
        this.fileNo = fileNo;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status){
        this.status = status;
    }

    public String getTip() {
        return tip;
    }

    public void setTip(String tip){
        this.tip = tip;
    }

    public Long getCreated() {
        return created;
    }

    public void setCreated(Long created){
        this.created = created;
    }

    public Long getUpdated() {
        return updated;
    }

    public void setUpdated(Long updated){
        this.updated = updated;
    }

    public Integer getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Integer isDeleted){
        this.isDeleted = isDeleted;
    }

}