package com.szmtjk.business.bean;

import com.szmtjk.business.bean.base.BaseModelAndDO;

import java.io.Serializable;

/**
 * auto generated by code helper on 2019-01-22.
 */
public class BaseExamReservation extends BaseModelAndDO {
    /**
     * 姓名
     */
    private String name;
    /**
     * 性别  1：男  2：女
     */
    private Integer gender;
    /**
     * 身份证号
     */
    private String idNo;
    /**
     * 手机号
     */
    private String mobile;
    /**
     * 婚否 1：已婚  2：未婚
     */
    private Integer married;
    /**
     * 公司
     */
    private String company;
    /**
     * 体检套餐名
     */
    private String packageName;
    /**
     * 体检日期
     */
    private String examDate;
    /**
     * 备注
     */
    private String memo;
    /**
     * isDeleted
     */
    private Integer isDeleted;

    public String getName() {
        return name;
    }

    public void setName(String name){
        this.name = name;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender){
        this.gender = gender;
    }

    public String getIdNo() {
        return idNo;
    }

    public void setIdNo(String idNo){
        this.idNo = idNo;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile){
        this.mobile = mobile;
    }

    public Integer getMarried() {
        return married;
    }

    public void setMarried(Integer married){
        this.married = married;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company){
        this.company = company;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName){
        this.packageName = packageName;
    }

    public String getExamDate() {
        return examDate;
    }

    public void setExamDate(String examDate){
        this.examDate = examDate;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo){
        this.memo = memo;
    }

    public Integer getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Integer isDeleted){
        this.isDeleted = isDeleted;
    }

}