package com.szmtjk.business.bean;

import com.szmtjk.business.bean.base.BaseModelAndDO;

/**
 * auto generated by code helper on 2019-01-05.
 */
public class BaseUser extends BaseModelAndDO {
    /**
     * 用户名
     */
    private String userName;
    /**
     * 用户密码
     */
    private String userPass;
    /**
     * 手机号
     */
    private String mobile;
    /**
     * isDeleted
     */
    private Integer isDeleted;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName){
        this.userName = userName;
    }

    public String getUserPass() {
        return userPass;
    }

    public void setUserPass(String userPass){
        this.userPass = userPass;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile){
        this.mobile = mobile;
    }

    public Integer getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Integer isDeleted){
        this.isDeleted = isDeleted;
    }

}