package com.szmtjk.business.db.entity;

import com.szmtjk.business.bean.BaseExamReservation;

/**
 * auto generated by code helper on 2019-01-22.
 */
public class ExamReservationDO extends BaseExamReservation {

}
