package com.szmtjk.business.db.entity;

import com.szmtjk.business.bean.base.BaseDBQueryPage;

/**
 * auto generated by code helper on 2019-03-04.
 */
public class FileImportStatusDBQuery extends BaseDBQueryPage {

}
