package com.szmtjk.business.model;

import com.szmtjk.business.bean.BaseFileImportStatus;

/**
 * auto generated by code helper on 2019-03-04.
 */
public class FileImportStatus extends BaseFileImportStatus {

}
