package com.szmtjk.business.model;

import com.szmtjk.business.bean.base.BaseQueryPage;

/**
 * auto generated by code helper on 2019-03-04.
 */
public class FileImportStatusQuery extends BaseQueryPage {

}
